---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/8 11:22
---

---@class HeaderGUIClass
local HeaderGUIClass = DeclareClass("HeaderGUIClass", ClassLib.GUIClass)

function HeaderGUIClass:ctor()
    HeaderGUIClass.__super.AddSerialField(self, "RemoteAddress", "Header.RemoteAddress", false)
end

function HeaderGUIClass:Initialize(guiKit)
    HeaderGUIClass.__super.Initialize(self, guiKit)

    self:BeginLayout(LayoutType.Form)
    self:BeginLayout(LayoutType.HBox, 1, "地区:")
    DataService.RegionIndex = 1
    self:ComboBox(DataService:GetRegionTable(), "region_cbb", DataService.RegionIndex - 1)
    self:EndLayout()

    self:BeginLayout(LayoutType.HBox, 1, "设备:")
    self:ComboBox({}, "device_cbb", 0, 4)
    self:Button("刷新", "device_refresh_btn", 1)
    self:EndLayout()

    self:BeginLayout(LayoutType.HBox, 1, "远程连接:")
    self:LineField(self:GetSerialField("RemoteAddress"), "device_remote_lf", false, 1, "地址:端口")
    self:Button("连接", "device_remote_connect_btn")
    self:Button("断开连接", "device_remote_disconnect_btn")
    self:EndLayout()

    self:Button("开启adb服务", "device_startserver_btn")
    self:Button("停止adb服务", "device_stopserver_btn")
    self:EndLayout()

    CoroutineService:StartCoroutine(function()
        CoroutineService:WaitForTime(1)
        self:RefreshDevices()
    end)
end

function HeaderGUIClass:RefreshDevices()
    DataService.DeviceData = false

    local deviceList = ADBService:GetDevices()
    DataService.DeviceDataList = deviceList
    local deviceChars = { }
    if #deviceList == 1 then
        deviceChars[1] =  string.format("%s(%s)", deviceList[1].Name, deviceList[1].Status)
    elseif #deviceList ~= 0 then
        for i = 1, #deviceList do
            deviceChars[i] = string.format("%s(%s)", deviceList[i].Name, deviceList[i].Status)
        end
    end
    self:SetComboBoxItems("device_cbb", deviceChars)
end

function HeaderGUIClass:OnButtonClicked(objectName)
    if objectName == "device_refresh_btn" then
        self:RefreshDevices()
        return true
    elseif objectName == "device_startserver_btn" then
        ADBService:StartServer()
        return true
    elseif objectName == "device_stopserver_btn" then
        ADBService:KillServer()
        return true
    elseif objectName == "device_remote_connect_btn" then
        local address = self:GetLineFieldText("device_remote_lf")
        self:SetSerialField("RemoteAddress", address)
        if not ADBService:Connect(address) then
            LogE(string.format("连接%s失败", address))
        else
            LogD(string.format("连接%s成功", address))
            self:RefreshDevices()
        end
        return true
    elseif objectName == "device_remote_disconnect_btn" then
        local address = self:GetLineFieldText("device_remote_lf")
        if not ADBService:Disconnect(address) then
            LogE(string.format("断连%s失败", address))
        else
            LogD(string.format("断连%s成功", address))
            self:RefreshDevices()
        end
    end
end

function HeaderGUIClass:OnTextFieldChanged(objectName, text)
end

function HeaderGUIClass:OnComboBoxChanged(objectName, index)
    if objectName == "device_cbb" then
        DataService:SetDeviceIndex(index + 1)
        return true
    elseif objectName == "region_cbb" then
        DataService.RegionIndex = index + 1
        return true
    end
end