---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/8 11:22
---

---@class HeaderGUIClass
local HeaderGUIClass = DeclareClass("HeaderGUIClass", ClassLib.GUIClass)

function HeaderGUIClass:ctor()
    HeaderGUIClass.__super.AddSerialField(self, "RemoteAddress", "Header.RemoteAddress", false)
    HeaderGUIClass.__super.AddSerialField(self, "PackageName", "Header.PackageName", false)
end

function HeaderGUIClass:Initialize(guiKit)
    HeaderGUIClass.__super.Initialize(self, guiKit)

    self:BeginLayout(LayoutType.Form)
    self:BeginLayout(LayoutType.HBox, 1, "包名:")
    self:LineField(self:GetSerialField("PackageName"), "package_lf", false, 1)
    self:EndLayout()

    MDBService:SetPlatform(Platform.Android)
    self:RadioGroup(PlatformName, "平台", "platform_rg", 0, 1, 0)

    self:BeginLayout(LayoutType.HBox, 1, "设备:")
    self:ComboBox({}, "device_cbb", 0, 4)
    self:Button("刷新", "device_refresh_btn", 1)
    self:EndLayout()

    self:BeginLayout(LayoutType.HBox, 1, "远程设备或者模拟器连接(夜神127.0.0.1:62001):")
    self:LineField(self:GetSerialField("RemoteAddress"), "device_remote_lf", false, 1, "地址:端口")
    self:Button("连接", "device_remote_connect_btn")
    self:Button("断开连接", "device_remote_disconnect_btn")
    self:EndLayout()

    self:Button("开启adb服务", "device_startserver_btn")
    self:Button("停止adb服务", "device_stopserver_btn")
    self:EndLayout()

    CoroutineService:StartCoroutine(function()
        CoroutineService:WaitForTime(1)
        self:RefreshDevices()
    end)
end

function HeaderGUIClass:RefreshDevices()
    DataService.DeviceData = false

    local deviceList = MDBService:GetDevices()
    DataService.DeviceDataList = deviceList
    local deviceChars = { }
    if #deviceList == 1 then
        deviceChars[1] =  string.format("%s(%s)", deviceList[1].Alias, deviceList[1].Status)
    elseif #deviceList ~= 0 then
        for i = 1, #deviceList do
            deviceChars[i] = string.format("%s(%s)", deviceList[i].Alias, deviceList[i].Status)
        end
    end
    self:SetComboBoxItems("device_cbb", deviceChars)
end

function HeaderGUIClass:OnButtonClicked(objectName)
    if objectName == "device_refresh_btn" then
        self:RefreshDevices()
        return true
    elseif objectName == "device_startserver_btn" then
        MDBService:StartServer()
        return true
    elseif objectName == "device_stopserver_btn" then
        MDBService:KillServer()
        return true
    elseif objectName == "device_remote_connect_btn" then
        local address = self:GetLineFieldText("device_remote_lf")
        if MDBService:Connect(address) then
            self:RefreshDevices()
        end
        return true
    elseif objectName == "device_remote_disconnect_btn" then
        local address = self:GetLineFieldText("device_remote_lf")
        if  MDBService:Disconnect(address) then
            self:RefreshDevices()
        end
    end
end

function HeaderGUIClass:OnLineFieldChanged(objectName, text)
    if objectName == "package_lf" then
        DataService.PackageName = text
        self:SetSerialField("PackageName", text)
    elseif objectName == "device_remote_lf" then
        self:SetSerialField("RemoteAddress", text)
    end
end

function HeaderGUIClass:OnComboBoxChanged(objectName, index)
    if objectName == "device_cbb" then
        DataService:SetDeviceIndex(index + 1)
        return true
    end
end

function HeaderGUIClass:OnRadioGroupToggled(objectName, id, checked)
    if objectName == "platform_rg" then
        if checked then
            MDBService:SetPlatform(id + 1)
            DataService:SetDeviceIndex(0)
            self:SetComboBoxItems("device_cbb", null)
            LogD("切换到" .. PlatformName[id + 1])
            MDBService:KillProcess()
            CoroutineService:StartCoroutine(function()
                CoroutineService:WaitForTime(1)
                self:RefreshDevices()
            end)
        end
        return true
    end
end