---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/8 11:25
---

local DataServiceClass = DeclareClass("DataServiceClass")

function DataServiceClass:ctor()
    self._region = {
        {RegionName = "中国大陆", PackageName = "com.tencent.tmgp.sskgame"},
        {RegionName = "港澳台", PackageName = "com.tencent.tmgp.ssktw"},
        {RegionName = "东南亚", PackageName = "com.tencent.tmgp.ssksea"},
        {RegionName = "欧美", PackageName = "com.tencent.tmgp.sskeus"},
        {RegionName = "韩国", PackageName = "com.tencent.tmgp.sskkr"},
        {RegionName = "日本", PackageName = "com.tencent.tmgp.sskjp"}
    }

    self.DeviceData = false
    self.DeviceDataList = false
    self.RegionIndex = 0
end

function DataServiceClass:GetRegionTable()
    local regions = {}
    for i = 1, #self._region do
        regions[i] = string.format("%s(%s)", self._region[i].RegionName, self._region[i].PackageName)
    end

    return regions;
end

function DataServiceClass:SetDeviceIndex(index)
    if index <= 0 or index > #self.DeviceDataList then
        self.DeviceData = false
    else
        self.DeviceData = self.DeviceDataList[index]
    end
end

function DataServiceClass:GetDeviceName()
    if not self.DeviceData then
        return ""
    end

    return self.DeviceData.Name
end

function DataServiceClass:GetPackageName()
    return self._region[self.RegionIndex].PackageName
end

function DataServiceClass:GetObbPath()
    return string.format("/sdcard/Android/obb/%s/", self:GetPackageName())
end

function DataServiceClass:GetGameLogPath()
    return string.format("/sdcard/Android/data/%s/files/Log", self:GetPackageName())
end

function DataServiceClass:GetPkgBasePath()
    return string.format("/sdcard/Android/data/%s/files/Resources/PkgBase/", self:GetPackageName())
end

DataService = DataServiceClass.new()