---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/12 17:33
---

local IDBServiceClass = DeclareClass("IDBServiceClass")

function IDBServiceClass:ctor()
    self._proc = false
    self._taskName = ""
end

function IDBServiceClass:Initialize(processKit)
    self._proc = processKit
end

function IDBServiceClass:Install(uuid, ipaPath)
    LogD("idb install")
    self._taskName = "ideviceinstaller.exe"

    local cmd = string.format("-u %s -i %s", uuid, ipaPath)
    if self._proc.Start("libimobiledevice/ideviceinstaller.exe", cmd) ~= ExitCode.Success then
        LogE("安装文件失败：".. self._proc.GetError())
        self._taskName = ""
        return false
    end

    self._taskName = ""
    return true
end

function IDBServiceClass:Logcat(uuid, outputFilePath)
    LogD("idb logcat")
    self._taskName = ""
    local cmd =  string.format("/c %s/libimobiledevice/idevicesyslog.exe -u %s -x >%s", Path.GetCurrentPath(), uuid, outputFilePath)
    LogD(cmd)
    local result = self._proc.Start("cmd.exe", cmd)
    if result == ExitCode.Success or result == ExitCode.Crashed then
        return true
    end

    LogE("实时日志失败：".. self._proc.GetError())
    return false
end

function IDBServiceClass:Pull(uuid, bundleName, srcPath, dstPath)
    LogD("idb pull")
    self._taskName = "ifuse.exe"

    Path.TryRemoveDir("mnt")
    Path.TryMakeDir("mnt")

    local coroutine = CoroutineService:StartCoroutine(function()
        CoroutineService:WaitForTime(3)
        self:StopProcess()
    end)

    local exit = false
    local cmd = string.format("mnt -u %s --documents %s", uuid, bundleName)
    LogD(cmd)
    local result = self._proc.Start("ifuse/ifuse.exe", cmd)
    CoroutineService:StopCoroutine(coroutine)
    if result == ExitCode.Crashed or result == ExitCode.Success then
        Path.TryCopy("mnt/" .. srcPath, dstPath)
        exit = true
    end

    self._taskName = ""

    Path.TryRemoveDir("mnt")
    if not exit then
        LogE("获取文件失败: " .. self._proc.GetError())
    end
    return exit
end

function IDBServiceClass:StopProcess()
    LogD("stop proc")
    self._proc.Stop()
end

function IDBServiceClass:GetDevices()
    LogD("idb devices")
    self._taskName = "idevice_id.exe"

    if self._proc.Start("libimobiledevice/idevice_id.exe") ~= ExitCode.Success then
        self._taskName = ""
        LogE("获取设备失败：".. self._proc.GetError())
        return {}
    end

    self._taskName = ""

    local output = self._proc.GetOutput()
    local splits = string.split(output, "\n")
    if not splits then
        return {}
    end

    for i = #splits, 1, -1 do
        splits[i] = string.trim(splits[i], "\n")
        splits[i] = string.trim(splits[i], "\r")
        if not splits[i] or splits[i] == "" then
            table.remove(splits, i)
        end
    end

    local result = {}
    for i = 1, #splits do
        local data = string.split(splits[i], " ")
        local alias = ""
        local name = data[1]
        local status = data[2]
        if self._proc.Start("libimobiledevice/idevice_id.exe", name) == ExitCode.Success then
            alias = string.trim(self._proc.GetOutput(), "\n")
        end
        result[#result + 1] = {Name = name, Status = status, Alias = alias}
    end

    return result
end

function IDBServiceClass:ReportCrash(uuid, dir)
    LogD("idb crashreport")

    local result = self._proc.Start("libimobiledevice/idevicecrashreport.exe", string.format("-u %s %s", uuid, dir));
    if result ~= ExitCode.Success then
        LogE("获取崩溃日志失败：".. self._proc.GetError())
        return false
    end

    return true
end

function IDBServiceClass:KillProcess()
    if self._taskName and self._taskName ~= "" then
        self._proc.Start("cmd", string.format("/c taskkill /im %s /f", self._taskName))
    end
end