---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/10 15:40
---

local ExportTabGUIClass = DeclareClass("ExportTabGUIClass", ClassLib.TabGUIClass)

function ExportTabGUIClass:ctor()
    ExportTabGUIClass.__super.AddSerialField(self, "ExportDir", "Tool.Export.ExportDir", false)
    ExportTabGUIClass.__super.AddSerialField(self, "DeviceFilePath", "Tool.Export.DeviceFilePath", false)
end

function ExportTabGUIClass:vGetTabName()
    return "导出"
end

function ExportTabGUIClass:vGetLayoutType()
    return LayoutType.Form
end

function ExportTabGUIClass:vGetTabObjectName()
    return "export_tab"
end

function ExportTabGUIClass:vSetupWidgetUI()
    self:BeginLayout(LayoutType.HBox, 1, "导出目录")
    self:LineField(self:GetSerialField("ExprotDir"), "export_lf", true)
    self:Button("打开", "export_select_btn")
    self:EndLayout()

    self:LineField(self:GetSerialField("DeviceFilePath"), "src_lf", false, 1, "设备文件路径")

    self:Button("导出", "export_btn")
end

function ExportTabGUIClass:vOnButtonClicked(objectName)
    if objectName == "export_select_btn" then
        local exportDir = self:OpenDirDialog("导出目录", self:GetSerialField("ExportDir"))
        self:SetLineFieldText("export_lf", exportDir)
        self:SetSerialField("ExportDir", exportDir)
        return true
    elseif objectName == "export_btn" then
        self:Export()
    end
end

function ExportTabGUIClass:vOnLineFieldChanged(objectName, text)
    if objectName == "src_lf" then
        self:SetSerialField("DeviceFilePath", text)
        return true
    end
end

function ExportTabGUIClass:Export()
    if DataService.PackageName == "" then
        LogE("包名不能为空")
        return
    end

    local deviceName = DataService:GetDeviceName()
    local exportDir = self:GetSerialField("ExportDir")
    if exportDir == "" then
        LogE("导出目录不能为空")
        return
    end

    local deviceFilePath = self:GetLineFieldText("src_lf")
    if deviceFilePath == "" then
        LogE("设备文件路径不能为空")
        return
    end
    
    MDBService:Pull(deviceName, DataService:GetDataPath() .. deviceFilePath, exportDir)
end