---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/10 15:40
---

local GameLogTabGUIClass = DeclareClass("GameLogTabGUIClass", ClassLib.TabGUIClass)

function GameLogTabGUIClass:ctor()
    GameLogTabGUIClass.__super.AddSerialField(self, "LogDir", "Tool.GameLog.LogDir", false)
end

function GameLogTabGUIClass:vGetTabName()
    return "游戏日志"
end

function GameLogTabGUIClass:vGetLayoutType()
    return LayoutType.Form
end

function GameLogTabGUIClass:vGetTabObjectName()
    return "gamelog_tab"
end

function GameLogTabGUIClass:vSetupWidgetUI()
    self:BeginLayout(LayoutType.HBox, 1, "存放路径")
    self:LineField(self:GetSerialField("LogDir"), "gamelog_lf", true)
    self:Button("选择", "gamelog_select_btn")
    self:EndLayout()

    self:Button("获取", "gamelog_btn")
end

function GameLogTabGUIClass:vOnButtonClicked(objectName)
    if objectName == "gamelog_select_btn" then
        local logDir = self:OpenDirDialog("路径", self:GetSerialField("LogDir"))
        self:SetLineFieldText("gamelog_lf", logDir)
        self:SetSerialField("LogDir", logDir)
        return true
    elseif objectName == "gamelog_btn" then
        self:GrabGameLog()
    end
end

function GameLogTabGUIClass:GrabGameLog()
    local deviceName = DataService:GetDeviceName()
    if not deviceName or deviceName == "" then
        LogE("尚未连接设备")
        return
    end

    local logDir = self:GetSerialField("LogDir")
    if not logDir then
        LogE("请先选择路径")
        return
    end

    if not MDBService:Pull(deviceName, DataService:GetGameLogPath(), logDir, DataService:GetPackageName()) then
        LogE("获取失败")
        return
    end

    LogD("获取成功")
end