---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/8 10:51
---

local InstallTabGUIClass = DeclareClass("InstallTabGUIClass", ClassLib.TabGUIClass)

function InstallTabGUIClass:ctor()
    InstallTabGUIClass.__super.AddSerialField(self, "ApkPath", "Tool.Install.ApkPath", false)
    InstallTabGUIClass.__super.AddSerialField(self,"MainObbPath", "Tool.Install.MainObbPath", false)
    InstallTabGUIClass.__super.AddSerialField(self,"PatchObbPath", "Tool.Install.PatchObbPath", false)
end

function InstallTabGUIClass:vGetTabName()
    return "安装"
end

function InstallTabGUIClass:vGetLayoutType()
    return LayoutType.Form
end

function InstallTabGUIClass:vGetTabObjectName()
    return "install_tab"
end

function InstallTabGUIClass:vSetupWidgetUI()
    self:BeginLayout(LayoutType.HBox, 1, "安装包")
    self:LineField(self:GetSerialField("ApkPath"), "install_apk_lf", true)
    self:Button("浏览", "install_apk_btn")
    self:EndLayout()

    self:BeginLayout(LayoutType.HBox, 1, "主资源包")
    self:LineField(self:GetSerialField("MainObbPath"), "install_main_obb_lf", true)
    self:Button("浏览", "install_main_obb_btn")
    self:EndLayout()

    self:BeginLayout(LayoutType.HBox, 1, "副资源包")
    self:LineField(self:GetSerialField("PatchObbPath"), "install_patch_obb_lf", true)
    self:Button("浏览", "install_patch_obb_btn")
    self:EndLayout()

    self:Button("安装", "install_btn")
end

function InstallTabGUIClass:vOnButtonClicked(objectName)
    if objectName == "install_apk_btn" then
        local apkPath = self:OpenFileDialog("安装包", self:GetSerialField("ApkPath"), "Install File (*.apk *.ipa)")
        self:SetLineFieldText("install_apk_lf", apkPath)
        self:SetSerialField("ApkPath", apkPath)
        return true
    elseif objectName == "install_main_obb_btn" then
        local mainObbPath = self:OpenFileDialog("主资源包", self:GetSerialField("MainObbPath"), "Obb File (*.obb)")
        self:SetLineFieldText("install_main_obb_lf", mainObbPath)
        self:SetSerialField("MainObbPath", mainObbPath)
        return true
    elseif objectName == "install_patch_obb_btn" then
        local patchObbPath = self:OpenFileDialog("副资源包", self:GetSerialField("PatchObbPath"), "Obb File (*.obb)")
        self:SetLineFieldText("install_patch_obb_lf", patchObbPath)
        self:SetSerialField("PatchObbPath", patchObbPath)
        return true
    elseif objectName == "install_btn" then
        self:Install()
        return true
    end
end

function InstallTabGUIClass:vOnTextFieldChanged(objectName, text)

end

function InstallTabGUIClass:vOnComboBoxChanged(objectName, index)

end

function InstallTabGUIClass:Install()
    local deviceName = DataService:GetDeviceName()
    if not deviceName or deviceName == "" then
        LogE("未连接设备")
        return
    end

    local apkPath = self:GetSerialField("ApkPath")
    if not apkPath then
        LogE("无效的安装路径")
        return false
    end

    if not MDBService:Install(deviceName, apkPath) then
        LogE(apkPath .. "安装失败")
        return
    end

    local mainObbPath = self:GetSerialField("MainObbPath")
    if not mainObbPath then
        LogD("跳过主资源")
        LogD("安装完成")
        return
    end

    if not MDBService:Push(deviceName, mainObbPath, DataService:GetObbPath() .. Path.GetFileName(mainObbPath)) then
        LogE("主资源安装失败")
        return
    end

    local patchObbPath = self:GetSerialField("PatchObbPath")
    if not patchObbPath then
        LogD("跳过副资源")
        LogD("安装完成")
        return
    end

    if not MDBService:Push(deviceName, patchObbPath, DataService:GetObbPath() .. Path.GetFileName(patchObbPath)) then
        LogE("副资源安装失败")
        return
    end

    LogD("安装完成")
end