---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/10 18:00
---

local LogcatTabGUIClass = DeclareClass("LogcatTabGUIClass", ClassLib.TabGUIClass)

function LogcatTabGUIClass:ctor()
    LogcatTabGUIClass.__super.AddSerialField(self, "LogFilePath", "Tool.Logcat.LogFilePath", false)
end

function LogcatTabGUIClass:vGetTabName()
    return "Logcat"
end

function LogcatTabGUIClass:vGetLayoutType()
    return LayoutType.Form
end

function LogcatTabGUIClass:vGetTabObjectName()
    return "logcat_tab"
end

function LogcatTabGUIClass:vSetupWidgetUI()
    self:BeginLayout(LayoutType.HBox, 1, "输出文件")
    self:LineField(self:GetSerialField("LogFilePath"), "logcat_output_lf", true)
    self:Button("浏览", "logcat_explore_btn")
    self:EndLayout()

    self:Button("开始", "logcat_start_btn")
    self:Button("停止", "logcat_stop_btn")
end

function LogcatTabGUIClass:vOnButtonClicked(objectName)
    if objectName == "logcat_explore_btn" then
        local logFilePath = self:OpenFileDialog("输出文件", self:GetSerialField("LogFilePath"), "Log Files (*.txt *.log)")
        self:SetLineFieldText("logcat_output_lf", logFilePath)
        self:SetSerialField("LogFilePath", logFilePath)
        return true
    elseif objectName == "logcat_start_btn" then
        self:Start()
        return true
    elseif objectName == "logcat_stop_btn" then
        self:Stop()
    end
end

function LogcatTabGUIClass:Start()
    local deviceName = DataService:GetDeviceName()
    local logFilePath = self:GetSerialField("LogFilePath")

   MDBService:Logcat(deviceName, "v", "tag", logFilePath)
end

function LogcatTabGUIClass:Stop()
    MDBService:StopProcess()
end