---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/10 19:08
---

local ReplaceFileTabGUIClass = DeclareClass("ReplaceFileTabGUIClass", ClassLib.TabGUIClass)

function ReplaceFileTabGUIClass:ctor()
    ReplaceFileTabGUIClass.__super.AddSerialField(self, "FilePath", "Tool.ReplaceFile.FilePath", false)
    ReplaceFileTabGUIClass.__super.AddSerialField(self, "PkgBasePath", "Tool.ReplaceFile.PkgBasePath", false)
end

function ReplaceFileTabGUIClass:vGetTabName()
    return "替换文件"
end

function ReplaceFileTabGUIClass:vGetLayoutType()
    return LayoutType.Form
end

function ReplaceFileTabGUIClass:vGetTabObjectName()
    return "replacefile_tab"
end

function ReplaceFileTabGUIClass:vSetupWidgetUI()
    self:BeginLayout(LayoutType.HBox, 1, "替换文件")
    self:LineField(self:GetSerialField("FilePath"), "replacefile_lf", true)
    self:Button("浏览", "replacefile_explore_btn")
    self:EndLayout()

    self:LineField(self:GetSerialField("PkgBasePath"), "replacefile_pkgbase_lf", false, 1, "替换路径(PkgBase相对路径)")
    self:Button("替换", "replacefile_replace_btn")
end

function ReplaceFileTabGUIClass:vOnButtonClicked(objectName)
    if objectName == "replacefile_explore_btn" then
        local filePath = self:OpenFileDialog("替换文件", self:GetSerialField("FilePath"), "All File (*.*)")
        self:SetLineFieldText("replacefile_lf",  filePath)
        self:SetSerialField("FilePath", filePath)
        return true
    elseif objectName == "replacefile_replace_btn" then
        self:Replace()
    end
end

function ReplaceFileTabGUIClass:Replace()
    local deviceName = DataService:GetDeviceName()
    local pkgbasePath = self:GetLineFieldText("replacefile_pkgbase_lf")
    local filePath = self:GetSerialField("FilePath")

    self:SetSerialField("PkgBasePath", pkgbasePath)
    MDBService:Push(deviceName, filePath, DataService:GetPkgBasePath() .. string.gsub(pkgbasePath, "\\", "/") .. "/" .. Path.GetFileName(filePath))
end