---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/8 10:47
---

---@class TabGUIClass
local TabGUIClass = DeclareClass("TabGUIClass", ClassLib.GUIClass)

function TabGUIClass:ctor()
end

function TabGUIClass:vGetTabName()

end

function TabGUIClass:vGetLayoutType()

end

function TabGUIClass:vGetTabObjectName()

end

function TabGUIClass:vSetupWidgetUI()

end

function TabGUIClass:SetupUI()
    self:BeginTab(self:vGetTabName(), self:vGetLayoutType(), self:vGetTabObjectName())
    self:vSetupWidgetUI()
    self:EndTab()
end

function TabGUIClass:vOnButtonClicked(objectName)

end

function TabGUIClass:vOnTextFieldChanged(objectName, text)

end

function TabGUIClass:vOnLineFieldChanged(objectName, text)

end

function TabGUIClass:vOnComboBoxChanged(objectName, index)

end

function TabGUIClass:vOnRadioGroupToggled(objectName, id, checked)
end

function TabGUIClass:vOnTick(deltaTime)

end