---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/9/30 0:03
---

require("Plugins.Base.Declare")
require("Plugins.Base.Serializable")
require("Plugins.Base.GUI")
require("Plugins.Service.SerializeService")
require("Plugins.Service.ADBService")
require("Plugins.Service.CoroutineService")
require("Plugins.Service.DataService")
require("Plugins.HeaderGUI.HeaderGUI")
require("Plugins.ToolGUI.ToolGUI")
require("Plugins.ToolGUI.TabGUI.TabGUI")
require("Plugins.ToolGUI.TabGUI.InstallTabGUI")
require("Plugins.ToolGUI.TabGUI.GameLogTabGUI")
require("Plugins.ToolGUI.TabGUI.LogcatTabGUI")
require("Plugins.ToolGUI.TabGUI.ReplaceFileTabGUI")

---@type HeaderGUIClass
local headerGUI = false
---@type ToolGUIClass
local toolGUI = false

function Main(guiKit, procKit)
    SerializeService:Initialize()
    ADBService:Initialize(procKit)

    headerGUI = ClassLib.HeaderGUIClass.new()
    toolGUI = ClassLib.ToolGUIClass.new()
    headerGUI:Initialize(guiKit)
    toolGUI:Initialize(guiKit)
end

function OnDestroyed()
    ADBService:KillProc()
    SerializeService:Save()
end

function OnButtonClicked(objectName)
    if headerGUI:OnButtonClicked(objectName) then
        return
    end

    toolGUI:OnButtonClicked(objectName)
end

function OnTextFieldChanged(objectName, text)
    if headerGUI:OnTextFieldChanged(objectName, text) then
        return
    end

    toolGUI:OnTextFieldChanged(objectName, text)
end

function OnComboBoxChanged(objectName, index)
    if headerGUI:OnComboBoxChanged(objectName, index) then
        return
    end

    toolGUI:OnComboBoxChanged(objectName, index)
end

function OnTick(deltaTime)
    CoroutineService:OnTick(deltaTime)
end