---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/9/30 0:03
---

require("Plugins.Base.Declare")
require("Plugins.Base.Serializable")
require("Plugins.Base.GUI")
require("Plugins.Service.SerializeService")
require("Plugins.Service.ADBService")
require("Plugins.Service.IDBService")
require("Plugins.Service.MDBService")
require("Plugins.Service.CoroutineService")
require("Plugins.Service.DataService")
require("Plugins.HeaderGUI.HeaderGUI")
require("Plugins.ToolGUI.ToolGUI")
require("Plugins.ToolGUI.TabGUI.TabGUI")
require("Plugins.ToolGUI.TabGUI.InstallTabGUI")
require("Plugins.ToolGUI.TabGUI.GameLogTabGUI")
require("Plugins.ToolGUI.TabGUI.LogcatTabGUI")
require("Plugins.ToolGUI.TabGUI.ReplaceFileTabGUI")
require("Plugins.ToolGUI.TabGUI.ReportCrashTabGUI")

LogD = Log.LogD
LogW = Log.LogW
LogE = Log.LogE

local headerGUI = false
local toolGUI = false

function Main(guiKit, procKit)
    -- LogW("\niOS获取游戏日志功能需要以下条件才能正常执行：\n1、安装iTunes\n2、安装MDBGUI目录下ifuse/DokanSetup_redist.exe")
     LogW("\niOS目前只支持安装、实时日志和崩溃日志\nAndroid不支持崩溃日志")
    SerializeService:Initialize()
    MDBService:Initialize(procKit)
    headerGUI = ClassLib.HeaderGUIClass.new()
    toolGUI = ClassLib.ToolGUIClass.new()
    headerGUI:Initialize(guiKit)
    toolGUI:Initialize(guiKit)
end

function OnDestroyed()
    MDBService:KillProcess()
    SerializeService:Save()
end

function OnButtonClicked(objectName)
    if headerGUI:OnButtonClicked(objectName) then
        return
    end

    toolGUI:OnButtonClicked(objectName)
end

function OnTextFieldChanged(objectName, text)
    if headerGUI:OnTextFieldChanged(objectName, text) then
        return
    end

    toolGUI:OnTextFieldChanged(objectName, text)
end

function OnComboBoxChanged(objectName, index)
    if headerGUI:OnComboBoxChanged(objectName, index) then
        return
    end

    toolGUI:OnComboBoxChanged(objectName, index)
end

function OnRadioGroupToggled(objectName, id, checked)
    if headerGUI:OnRadioGroupToggled(objectName, id, checked) then
        return
    end

    toolGUI:OnComboBoxChanged(objectName, id, checked)
end

function OnTick(deltaTime)
    CoroutineService:OnTick(deltaTime)
end