---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by musmusliu.
--- DateTime: 2021/10/11 9:48
---

local SerializableClass = DeclareClass("SerializableClass")

function SerializableClass:ctor()
    self._serials = {}
end

function SerializableClass:AddSerialField(fieldName, serializeKey, default)
    self[fieldName] = SerializeService:ReadValue(serializeKey, default)
    self._serials[fieldName] = serializeKey
end

function SerializableClass:SetSerialField(fieldName, value)
    local key = self._serials[fieldName]
    if not key then
        return
    end

    self[fieldName] = value
    SerializeService:WriteValue(key, value, false)
end

function SerializableClass:GetSerialField(fieldName)
    return self[fieldName]
end